spring:
  profiles:
    active: dev
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

server:
  servlet:
    encoding:
      force: true